name: CI

on:
  workflow_call:
    inputs:
      node-version:
        description: Node.js version
        type: string
        default: '22'

jobs:
  check-version:
    uses: yarkivaev/npm-workflows/.github/workflows/check-version.yml@main

  lint:
    uses: yarkivaev/npm-workflows/.github/workflows/lint.yml@main
    with:
      node-version: ${{ inputs.node-version }}

  test:
    uses: yarkivaev/npm-workflows/.github/workflows/test.yml@main
    with:
      node-version: ${{ inputs.node-version }}
